packages:
  - packages/internal
  - packages/svelte-site
  - packages/bluesky-post-embed
  - packages/bluesky-profile-card-embed
  - packages/bluesky-profile-feed-embed

allowBuilds:
  esbuild: false

catalog:
  svelte: ^5.56.8

minimumReleaseAgeExclude:
  - vite@8.2.1
  - vite-prerender-plugin@0.5.13
